export const UPDATE_PROMOCODE = "UPDATE_PROMOCODE";
export const UPDATE_PROMOCODE_SUCCESS = "UPDATE_PROMOCODE_SUCCESS";
export const UPDATE_PROMOCODE_FAILED = "UPDATE_PROMOCODE_FAILED";

export const SEARCH_PROMOCODE = "SEARCH_PROMOCODE";